create table if not exists projects(
    id integer primary key generated by default as identity,
    name text not null check (name <> ''),
    priority integer not null,
    description text,
    deliverydate date not null
);


create table if not exists tasks(

    id integer primary key generated by default as identity,
    name text not null check (name <> ''),
    done boolean,
    projectID integer references projects(id)


);

--insert data in projects

insert into projects(name, priority, description, deliverydate) values('Make a web app', 1, 'Using Javascript','2019-05-12');

--insert data in tasks

insert into tasks(name, done, projectID) values ('define model',false,1);

insert into tasks(name, done, projectID) values ('Download flutter',false,2);

insert into tasks(name, done, projectID) values ('Design',false,2);


